### ISSUE TITLE
Use firstboot script to set ULA address

### ISSUE THREAD

**Issue by stephen304** [MassMesh/meta-imagebuilder#37]
In `communities/massmesh/meshnode/files/etc/uci-defaults/zz-massmesh-firstboot.sh` (when merged) we should set the ula address with the 3xx subnet from yggdrasil. The challenge is that yggdrasil is not running when firstboot runs, but `/etc/yggdrasil.conf` seems to have been generated by then, so we may be able to calculate the subnet using the config + jq to extract information.

**Comment by stephen304** [comment]
Neil added `-subnet` which does exactly what we need

`yggdrasil -useconffile /etc/yggdrasil.conf -subnet`

**Comment by wfleurant** [comment]
waiting on next yggdrasil release -- or we could submit a patch to backport this harmless feature.. I think next release is imminent, so.. give this ~5 days before we backport a patch

**Comment by wfleurant** [comment]
re: the ~5day estimate  

if this is merged in the next day or so, will unblock this feature https://github.com/openwrt/packages/pull/10584

**Comment by wfleurant** [comment]
currently a default route is set on the connected device

it should work, as tested nearly a year ago. be it default gw via either example:
- 301:8569:5531:388a::1
- fe80::dea6:32ff:fe1f:3abf
