### ISSUE TITLE
Validate / discuss 300 subnet "natting" behavior

### ISSUE THREAD

**Issue by stephen304** [MassMesh/meta-imagebuilder#38]
We may want to tweak the zone forwarding rules to make the 300 block behave like NAT+firewall. Anyone wanting to host a service should be technical enough to create a forward / rule and this will protect laypeople better. We should discuss briefly.

**Comment by wfleurant** [comment]
related: https://github.com/openwrt/odhcpd/pull/33

**Comment by wfleurant** [comment]
odhcpd from z and ruygg
> by the way, have you tried to announce 300::/8 subnet and 200::/7 route to LAN clients?

**Comment by stephen304** [comment]
Via RA? Imo the current dhcpv6 behavior seems adequate. This ticket is re: v6 firewall behavior

**Comment by wfleurant** [comment]
so right now, i can get a 300::/64 address assigned via ULA but the big question remains do we firewall clients from the mesh.

mmm... yah.

**Comment by wfleurant** [comment]
to prevent traffic from mesh zone yggdrasil from entering lan zone 300::

1. go to Firewall - Zone Settings
1. under `Zone ⇒ Forwardings` look for `yggdrasil ⇒ lan`
1. click the edit button
1. find and deselect   `Allow forward to destination zones`
1. save and apply. 

```
firewall.cfg1aad58=forwarding
firewall.cfg1aad58.src='yggdrasil'
firewall.cfg1aad58.dest='lan'
```

to revert, and allow mesh zone to reach 300::/64 network
```
uci add firewall forwarding # =cfg1aad58
uci set firewall.@forwarding[-1].src='yggdrasil'
uci set firewall.@forwarding[-1].dest='lan'
```

**Comment by wfleurant** [comment]
another thing, is at the gateway node, we may want to enable input to the device.  
while testing I may have set it the default Input policy on zone yggdrasil to reject.  
if set to reject, then traffic from gateway to ie: 10.42.42.200 will not work. 

`From 10.42.42.200 icmp_seq=1 Destination Port Unreachable`

**Comment by wfleurant** [comment]
![image](https://user-images.githubusercontent.com/5460439/91563266-dcceb580-e93e-11ea-9521-ceb3613a4480.png)

**Comment by wfleurant** [comment]
![image](https://user-images.githubusercontent.com/5460439/91563355-fcfe7480-e93e-11ea-985b-30156b8378b8.png)

**Comment by JamesVorder** [comment]
@stephen304 Do we want to add the firewall rule that @wfleurant mentioned above to our node builds by default? Seems straight-forward enough to me.

**Comment by stephen304** [comment]
I believe this is already done, it's easy to test in case we left it disabled.

Edit: I think we just need to remove lan from the yggdrasil forward.

**Comment by stephen304** [comment]
#98
