### ISSUE TITLE
/dev/shm is not executable on CI

### ISSUE THREAD

**Issue by stephen304** [MassMesh/meta-imagebuilder#6]
`target-metadata.pl` fails to execute on CI when using /dev/shm. Reverting the location fixes the issue. /dev/shm is probably noexecute on CI. Maybe we can detect this and fall back to 
```
IB_DIR="$ROOT_DIR/imagebuilder/$BASE_PATH"	  	# where to store imagebuilders
```

**Comment by wfleurant** [comment]
may be it was here 8bb57d8cd0b439 or #17 ?
