### ISSUE TITLE
Organize downloads.massmesh.net

### ISSUE THREAD

**Issue by wfleurant** [MassMesh/meta-imagebuilder#74]
*First agree on a plan :)*
- master --> snapshots
- branches --> experimental
- manually drop things into release
  - Something about tagging?
- Document this strategy on the wiki.

**Comment by wfleurant** [comment]
> heads up, metaimagebuilder builds will now end up under `https://downloads.massmesh.net/experimental/` until we finally switch back to the master branch, builds from which will go in `https://downloads.massmesh.net/snapshots/`

**Comment by JamesVorder** [comment]
@cure this is done, no? Only thing left is to document it on the wiki...

**Comment by cure** [comment]
@JamesVorder and @wfleurant yes, I've just documented things at https://massmesh.org/wiki/index.php?title=Build_infrastructure, feel free to improve that page if necessary. Closing this issue now.
